# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python Package

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.7, 3.8, 3.9, 3.10, pypy3]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        # if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        pip install .
    - name: Run MyPy check
      if: "matrix.python-version != 'pypy3'"
      run: |
        python -m pip install mypy
        mypy snr --ignore-missing-imports
    - name: Run Python unittests
      run: |
        python -m unittest
    - name: Create Package distribution
      run: |
        python setup.py check
        python setup.py build
        python setup.py sdist
